# 使用 minimal-mistakes 远程主题
theme: jekyll-theme-primer
plugins:
  - jekyll-remote-theme
title: "我的私人日记站"
paginate: 5             # 首页文章分页：每页显示5篇
# 注销掉旧主题
# theme: jekyll-theme-primer

# 使用 Modernist
theme: jekyll-theme-modernist

title: "我的私人日记站"
description: "记录日常、心情与回忆"

